services:
  bot:
    build: .
    container_name: vinted-telegram-bot
    restart: always
    env_file: .env
    volumes:
      - bot-data:/app/data
      - bot-logs:/app/logs

volumes:
  bot-data:
  bot-logs:
